import {test} from 'node:test';
import assert from 'node:assert/strict';
import {focusEstimate,focusBlocks,monthCells,syncPriorities,materializeDayPlan} from '../lib/workspace/day-plan';
import {importCalendar,calendarFeedUrl} from '../lib/workspace/ical';
import {useFocusStore,POMO_DURATIONS} from '../lib/store';
import {collectSnapshot,snapshotOf} from '../lib/workspace/snapshot';
test('Focus blocks round each chosen step and count only intervening pauses',()=>{assert.deepEqual(focusEstimate([{minutes:60},{minutes:15}]),{minutes:75,units:3,breaks:2,scheduled:155});assert.equal(focusBlocks([{id:'a',title:'A',minutes:60},{id:'b',title:'B',minutes:15}]).map(x=>x.id).join(','),'a:0,a:1,b:0');assert.equal(focusEstimate([]).units,0);});
test('Focus clock uses deadlines after a background delay and pauses safely',()=>{const f=useFocusStore.getState();f.startPlan([{id:'a',title:'A',part:1}]);useFocusStore.setState({deadline:Date.now()-1000});f.tickPomodoro();assert.equal(useFocusStore.getState().pomodoroSeconds,0);assert.equal(useFocusStore.getState().pomodoroRunning,false);f.advancePomodoro();assert.equal(useFocusStore.getState().pomodoroMode,'break');assert.equal(useFocusStore.getState().pomodoroSeconds,600);f.advancePomodoro();assert.equal(useFocusStore.getState().pomodoroSeconds,2700);f.stopPomodoro();assert.equal(useFocusStore.getState().planQueue.length,0);assert.equal(POMO_DURATIONS.focus,2700);});
test('Day plan retains chance reflections and uses the same first three priorities',()=>{const days={'organization:2026-10-03':{top:['old','',''],opportunity:'Eine echte Chance',gratitude:'Danke',learned:'Lernen',goal:'g'}};const items=[{id:'a',sourceKind:'goal' as const,sourceId:'g',title:'Ziel',date:'2026-10-03',workspace:'organization' as const,minutes:45,done:true}];const result=syncPriorities({days,workspace:'organization'},items,'2026-10-03');assert.equal(result['organization:2026-10-03'].opportunity,'Eine echte Chance');assert.deepEqual(result['organization:2026-10-03'].top,['Ziel','','']);assert.deepEqual(result['organization:2026-10-03'].completed,[true,false,false]);});
test('Month grid starts Monday and includes leap day exactly once',()=>{const grid=monthCells('2024-02-12');assert.equal(grid.length,42);assert.equal(new Date(grid[0]+'T12:00:00').getDay(),1);assert.equal(grid.filter(x=>x==='2024-02-29').length,1);});
const wrap=(body:string)=>'BEGIN:VCALENDAR\r\nVERSION:2.0\r\n'+body+'\r\nEND:VCALENDAR';
test('ICS handles recurring exceptions, exclusions, all-day spans and idempotent IDs',()=>{const text=wrap('BEGIN:VEVENT\r\nUID:weekly\r\nDTSTART:20261001T100000Z\r\nDTEND:20261001T110000Z\r\nRRULE:FREQ=DAILY;COUNT=3\r\nEXDATE:20261002T100000Z\r\nSUMMARY:Original\r\nEND:VEVENT\r\nBEGIN:VEVENT\r\nUID:weekly\r\nRECURRENCE-ID:20261003T100000Z\r\nDTSTART:20261003T120000Z\r\nDTEND:20261003T130000Z\r\nSUMMARY:Verschoben\r\nEND:VEVENT\r\nBEGIN:VEVENT\r\nUID:holiday\r\nDTSTART;VALUE=DATE:20261005\r\nDTEND;VALUE=DATE:20261007\r\nSUMMARY:Auszeit\r\nEND:VEVENT');const r=importCalendar(text,'cal',2026);assert.equal(r.events.length,4);assert.equal(r.events.find(e=>e.date==='2026-10-03')?.title,'Verschoben');assert.deepEqual(r.events.filter(e=>e.title==='Auszeit').map(e=>e.date),['2026-10-05','2026-10-06']);assert.deepEqual(r.events.map(e=>e.id),importCalendar(text,'cal',2026).events.map(e=>e.id));});
test('ICS refuses missing time zones, pathological frequency and overlong files',()=>{const r=importCalendar(wrap('BEGIN:VEVENT\r\nUID:x\r\nDTSTART;TZID=Unknown/Place:20261001T090000\r\nSUMMARY:Unknown\r\nEND:VEVENT'),'cal',2026);assert.equal(r.events.length,0);assert.equal(r.warnings.length,1);assert.throws(()=>importCalendar('x'.repeat(2000001),'c',2026));assert.equal(importCalendar(wrap('BEGIN:VEVENT\r\nUID:x\r\nDTSTART:20261001T090000Z\r\nRRULE:FREQ=SECONDLY\r\nEND:VEVENT'),'c',2026).events.length,0);});
test('Feed fetch permits provider paths only, never private hosts or redirects',()=>{assert.equal(calendarFeedUrl('https://127.0.0.1/calendar/ical/x'),null);assert.equal(calendarFeedUrl('https://calendar.google.com.evil.test/calendar/ical/x'),null);assert.equal(calendarFeedUrl('https://calendar.google.com/calendar/ical/x'), 'https://calendar.google.com/calendar/ical/x');assert.equal(calendarFeedUrl('webcal://p123-caldav.icloud.com/published/2/test'),'https://p123-caldav.icloud.com/published/2/test');assert.equal(calendarFeedUrl('https://calendar.google.com:444/calendar/ical/x'),null);});
test('Cloud snapshots strip subscription URLs and retain journal/plan data',()=>{const temporal=JSON.stringify({state:{calendars:[{id:'c',name:'Kalender',url:'https://calendar.google.com/calendar/ical/private-value',color:'#8462ac',visible:true,provider:'google',type:'private'}],events:[{id:'e',calendarId:'c',title:'Termin',date:'2026-10-03'}]},version:0});const snapshot=collectSnapshot({getItem:()=>temporal},['trinity-temporal-v2']);assert.equal(JSON.parse(snapshot.stores['trinity-temporal-v2']!).state.calendars[0].url,'');assert.equal(JSON.parse(snapshot.stores['trinity-temporal-v2']!).state.events.length,1);assert.throws(()=>snapshotOf({version:1,stores:{'trinity-temporal-v2':temporal}}));});

test('Old priorities are immediately available to focus and preserve blank-slot completion indices',()=>{const state={workspace:'organization' as const,planItems:[],days:{'organization:2026-10-03':{top:['','Priorität',''],completed:[false,true,false],opportunity:'Chance',gratitude:'',learned:'',goal:''}}};const result=materializeDayPlan(state,'2026-10-03');assert.equal(result.length,1);assert.equal(result[0].done,true);assert.equal(result[0].title,'Priorität');assert.equal(materializeDayPlan({...state,planItems:result},'2026-10-03').length,1);});
