'use client';
import {useEffect,useState} from 'react';
import {getNakshatra,getKinForDate,isPortalDay,upcomingPortalDays,SEAL_MEANINGS,TONE_MEANINGS,ZODIAC_MEANINGS,MOON_PHASE_MEANINGS,CH_ELEMENT_MEANINGS,CH_ANIMAL_MEANINGS} from '@/lib/astroNow';
import {getMoonPhase} from '@/lib/moon';
import {skyNow,chineseYear,chineseMonth} from '@/lib/workspace/cosmos';
export function AstroLegacyPanel(){
 const [now,setNow]=useState<Date|null>(null);useEffect(()=>{setNow(new Date());const id=setInterval(()=>setNow(new Date()),60000);return()=>clearInterval(id)},[]);
 if(!now)return <p role="status">Dein Tageskompass wird vorbereitet …</p>;
 const year=chineseYear(now),month=chineseMonth(now);
 const nak=getNakshatra(now),sky=skyNow(now),moon=getMoonPhase(now),kin=getKinForDate(now),tone=(kin-1)%13+1,seal=Object.keys(SEAL_MEANINGS)[(kin-1)%20];
 return <section className="astro-legacy"><div className="w-page-heading"><div><span className="w-eyebrow">AKTUELLE ENERGIEN · WIEDERGEFUNDEN</span><h2>Ein Blick in deinen Himmel.</h2><p>{now.toLocaleDateString('de-AT',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</p></div></div><div className="s-grid">{[['Westliche Sonne',`${sky.western.icon} ${sky.western.name}`,ZODIAC_MEANINGS[sky.western.name]],['Chinesisches Jahr',`${year.icon} ${year.name}`,`${CH_ELEMENT_MEANINGS[year.element]} ${CH_ANIMAL_MEANINGS[year.name.split('-')[1]]||''}`],['Chinesischer Sonnenmonat',`${month.icon} ${month.name}`,CH_ELEMENT_MEANINGS[month.element]],['Vedisches Mondhaus',`${nak.name} · Pada ${nak.pada}`,nak.keyword],['Mondphase',`${moon.emoji} ${moon.phase} · ${moon.illumination}%`,MOON_PHASE_MEANINGS[moon.phase]],['Maya · Dreamspell',`Kin ${kin} · ${seal}`,`${SEAL_MEANINGS[seal]} ${TONE_MEANINGS[tone]}`]].map(([label,title,detail])=><article className="w-card" key={label}><span className="w-eyebrow">{label}</span><h3>{title}</h3><p>{detail}</p></article>)}</div><section className="w-card"><h3>Mondphasen im {now.toLocaleDateString('de-AT',{month:'long'})}</h3><div className="astro-moon-month">{Array.from({length:new Date(now.getFullYear(),now.getMonth()+1,0).getDate()},(_,i)=>{const date=new Date(now.getFullYear(),now.getMonth(),i+1,12),m=getMoonPhase(date);return <div key={i} data-today={i+1===now.getDate()||undefined} title={`${i+1}. ${m.phase} · ${m.illumination}%`}><span>{m.emoji}</span><strong>{i+1}</strong></div>})}</div><p className="w-muted">Nächster Vollmond ungefähr in {moon.daysToFull} Tagen · Neumond in {moon.daysToNew} Tagen.</p></section><section className="w-card"><h3>Dreamspell-Portaltage</h3>{isPortalDay(now)&&<p>Heute ist nach dem wiederhergestellten Dreamspell-Kalender ein Portaltag.</p>}<ul>{upcomingPortalDays(now,5).map(p=><li key={p.date.toISOString()}>{p.date.toLocaleDateString('de-AT',{weekday:'short',day:'numeric',month:'long'})} · Kin {p.kin}</li>)}</ul><p className="w-muted">Die früheren Deutungen sind symbolische Reflexionsimpulse. Nakshatra und Mondvorschau verwenden die damaligen Näherungen; Dreamspell ist eine moderne Tradition.</p></section></section>;
}
