"use client";
import {useState} from 'react';
import {Plus,RefreshCw,Trash2} from 'lucide-react';
import {useTemporalStore,type CalendarSource} from '@/lib/store';

import {Dialog} from './Dialog';
export function CalendarSources({year}:{year:number}){
 const s=useTemporalStore(),[open,setOpen]=useState(false),[name,setName]=useState(''),[url,setUrl]=useState(''),[color,setColor]=useState('#8462ac'),[provider,setProvider]=useState<CalendarSource['provider']>('google'),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[text,setText]=useState('');
 async function load(cal?:CalendarSource){setBusy(true);setStatus('');try{let content=text;const sourceUrl=cal?.url||url;if(sourceUrl){const r=await fetch('/api/calendar/feed',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:sourceUrl})});const d=await r.json();if(!r.ok)throw Error(d.error);content=d.text;}if(!content&&provider!=='local'&&!cal)throw Error('Bitte eine ICS-Datei oder einen Abonnementlink wählen.');const id=cal?.id??crypto.randomUUID();const imported=content?(await import('@/lib/workspace/ical')).importCalendar(content,id,year):{events:[],warnings:[]};const state=useTemporalStore.getState();const next:CalendarSource=cal??{id,name:name.trim(),url:sourceUrl?sourceUrl.replace(/^webcal:/,'https:'):'',provider,type:'private',visible:true,color};if(!next.name)throw Error('Bitte einen Namen eingeben.');useTemporalStore.setState({calendars:cal?state.calendars:[...state.calendars,next],events:[...state.events.filter(e=>e.calendarId!==id||!e.imported||!e.date.startsWith(String(year))),...imported.events]});setStatus(imported.events.length+' Termine für '+year+' übernommen. '+imported.warnings.join(' '));if(!cal){setName('');setUrl('');setText('');setOpen(false);}}catch(e){setStatus(e instanceof Error?e.message:'Import fehlgeschlagen.');}finally{setBusy(false);}}
 return <section className="w-card calendar-sources"><div className="w-section-head"><span className="w-eyebrow">MEINE KALENDER</span><button className="w-icon" aria-label="Kalender einbinden" onClick={()=>setOpen(true)}><Plus size={18}/></button></div>{s.calendars.map(c=><div className="calendar-source" key={c.id}><label><input type="checkbox" checked={c.visible} onChange={()=>s.toggleCalendar(c.id)}/><i style={{background:c.color}}/><span>{c.name}</span></label>{c.url&&<button className="w-icon" disabled={busy} aria-label={c.name+' aktualisieren'} onClick={()=>void load(c)}><RefreshCw size={13}/></button>}{!['priv-default','assoc-default'].includes(c.id)&&<button className="w-icon" aria-label={c.name+' entfernen'} onClick={()=>{if(confirm('Diesen Kalender und seine importierten Termine auf diesem Gerät entfernen?'))useTemporalStore.setState({calendars:s.calendars.filter(x=>x.id!==c.id),events:s.events.filter(e=>e.calendarId!==c.id)});}}><Trash2 size={13}/></button>}</div>)}{status&&<p role="status">{status}</p>}
 {open&&<Dialog title="Kalender einbinden" onClose={()=>setOpen(false)}><form className="w-form" onSubmit={e=>{e.preventDefault();void load();}}><label>Name<input autoFocus required value={name} onChange={e=>setName(e.target.value)} maxLength={100}/></label><div className="w-form-row"><label>Kalender<select value={provider} onChange={e=>setProvider(e.target.value as CalendarSource['provider'])}><option value="google">Google</option><option value="apple">Apple / iCloud</option><option value="ical">Andere · ICS-Datei</option><option value="local">Eigener Kalender</option></select></label><label>Farbe<input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label></div>{provider!=='local'&&<><label>ICS-Abonnementlink · optional<input type="text" value={url} onChange={e=>setUrl(e.target.value)} maxLength={2048} placeholder="https://… oder webcal://…"/></label><label>Oder Kalenderdatei<input type="file" accept=".ics,text/calendar" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>2_000_000){setStatus('Bitte eine Datei unter 2 MB wählen.');return;}setText(await f.text());setUrl('');}}/></label><p>Google: Einstellungen → Kalender integrieren → iCal-Adresse. Apple: Kalender teilen → öffentlicher Kalender → Link kopieren. Alternativ privat eine ICS-Datei exportieren und hier importieren.</p><p>Importiert wird {year}. Abonnements lassen sich mit ↻ aktualisieren. Der Kalender wird nur gelesen; Änderungen hier werden nicht zurückgeschrieben. Ein Freigabelink kann persönliche Termine zugänglich machen: nur verwenden, wenn diese Freigabe für dich passt.</p></>}{status&&<p role="status">{status}</p>}<button disabled={busy} className="w-btn w-btn-primary">{busy?'Wird geladen …':'Kalender hinzufügen'}</button></form></Dialog>}</section>;
}
