"use client";
import {ChevronLeft,ChevronRight,Plus} from 'lucide-react';
import {useTemporalStore,type CalendarEvent} from '@/lib/store';
import {monthCells} from '@/lib/workspace/day-plan';
import {shiftMonth} from '@/lib/workspace/planner';
export function CalendarOverview({date,setDate,onEvent,onNew,view="both",onDay,onMonth}:{date:string;setDate:(date:string)=>void;onEvent:(e:CalendarEvent)=>void;onNew:()=>void;view?:"month"|"year"|"both";onDay?:()=>void;onMonth?:()=>void}){
 const s=useTemporalStore(),year=Number(date.slice(0,4)),visible=s.events.filter(e=>s.calendars.some(c=>c.id===e.calendarId&&c.visible)),color=(id:string)=>s.calendars.find(c=>c.id===id)?.color;
 return <div className="calendar-overview" data-view={view}>{view!=="year"&&<section className="w-card calendar-month"><header><div><span className="w-eyebrow">DEIN MONAT</span><h2>{new Date(date+'T12:00:00').toLocaleDateString('de-AT',{month:'long',year:'numeric'})}</h2></div><div><button className="w-icon" aria-label="Vorheriger Monat" onClick={()=>setDate(shiftMonth(date,-1))}><ChevronLeft size={18}/></button><button className="w-icon" aria-label="Nächster Monat" onClick={()=>setDate(shiftMonth(date,1))}><ChevronRight size={18}/></button></div></header><div className="month-weekdays">{['Mo','Di','Mi','Do','Fr','Sa','So'].map(d=><span key={d}>{d}</span>)}</div><div className="month-days">{monthCells(date).map(day=>{const events=visible.filter(e=>e.date===day);return <div key={day} className="month-day" data-outside={!day.startsWith(date.slice(0,7))} data-selected={day===date}><div className="month-day-head"><button aria-label={'Tag '+day+' auswählen'} onClick={()=>{setDate(day);onDay?.();}}>{Number(day.slice(8))}</button><button aria-label={'Termin am '+day+' planen'} onClick={()=>{setDate(day);onNew();}}><Plus size={12}/></button></div>{events.slice(0,4).map(e=><button key={e.id} className="month-event" style={{'--event-color':color(e.calendarId)} as React.CSSProperties} title={e.title} onClick={()=>{setDate(day);onEvent(e);}}><small>{e.startTime}</small>{e.title}</button>)}{events.length>4&&<button className="month-more" onClick={()=>{setDate(day);onDay?.();}}>+{events.length-4} weitere</button>}</div>;})}</div></section>}{view!=="month"&&<section className="w-card calendar-year"><header><h2>{year}</h2><button className="w-icon" aria-label="Vorheriges Jahr" onClick={()=>setDate(shiftMonth(date,-12))}><ChevronLeft size={15}/></button><button className="w-icon" aria-label="Nächstes Jahr" onClick={()=>setDate(shiftMonth(date,12))}><ChevronRight size={15}/></button></header><div className="year-months">{Array.from({length:12},(_,i)=>{const month=year+'-'+String(i+1).padStart(2,'0');const cells=monthCells(month+'-01').filter(d=>d.startsWith(month));const offset=(new Date(month+'-01T12:00:00').getDay()+6)%7;return <section key={month}><button className="year-month-name" onClick={()=>{setDate(month+'-01');onMonth?.();}}>{new Date(year,i,1).toLocaleDateString('de-AT',{month:'short'})}</button><div className="year-days">{Array.from({length:offset},(_,j)=><span key={'empty'+j}/>)}{cells.map(day=>{const colors=[...new Set(visible.filter(e=>e.date===day).map(e=>color(e.calendarId)))];return <span className="year-day" key={day} title={day+(colors.length?' · belegt':' · frei')}>{Number(day.slice(8))}<span>{colors.slice(0,3).map(c=><i key={c} style={{background:c}}/>)}</span></span>;})}</div></section>;})}</div></section>}</div>;
}
