"use client";
import {useState,useEffect} from 'react';
import {Plus,Play,ArrowUp,ArrowDown,Check,X,Clock} from 'lucide-react';
import {usePersonal,inWorkspace,type PlanItem} from '@/lib/workspace/personal';
import {useTemporalStore,useFocusStore,useAuthStore} from '@/lib/store';
import {useBoard} from '@/lib/workspace/useBoard';
import {boardTasks} from '@/lib/workspace/board';
import {focusBlocks,focusEstimate,syncPriorities,minutesBetween,materializeDayPlan} from '@/lib/workspace/day-plan';
import {localDate} from '@/lib/workspace/time';
import {Dialog} from './Dialog';
export type PlanCandidate={id:string;title:string;minutes:number;kind:PlanItem['sourceKind'];sourceId:string;location?:PlanItem['location']};
export function usePlanCandidates(date:string){const s=usePersonal(),t=useTemporalStore(),{board}=useBoard(),user=useAuthStore(x=>x.user);return [
 ...s.goals.filter(g=>inWorkspace(g,s.workspace)&&!g.done).map(g=>({id:'goal:'+g.id,sourceId:g.id,kind:'goal' as const,title:g.title,minutes:g.minutes||45,location:g.location})),
 ...s.notes.filter(n=>inWorkspace(n,s.workspace)).map(n=>({id:'note:'+n.id,sourceId:n.id,kind:'note' as const,title:n.title,minutes:n.minutes||15,location:n.location})),
 ...t.events.filter(e=>e.date===date&&t.calendars.some(c=>c.id===e.calendarId&&c.visible)).map(e=>({id:'event:'+e.id,sourceId:e.id,kind:'event' as const,title:e.title,minutes:minutesBetween(e.startTime,e.endTime),location:e.location})),
 ...board.projects.filter(p=>!p.ownerId||p.ownerId===user?.name||p.sharedWith==='all').map(p=>({id:'project:'+p.id,sourceId:p.id,kind:'project' as const,title:p.name,minutes:45})),
 ...boardTasks(board,user?.name??null).filter(t=>!t.done).map(t=>({id:'task:'+t.id,sourceId:t.id,kind:'task' as const,title:t.title,minutes:45})),
 ];}
export function DayPlan({date=localDate(),onPlace}:{date?:string;onPlace?:(location:PlanItem['location'])=>void}){
 const s=usePersonal(),sources=usePlanCandidates(date),[picker,setPicker]=useState(false),[q,setQ]=useState(''),[start,setStart]=useState(''),[drag,setDrag]=useState('');
 const allItems=materializeDayPlan(s,date);
 const items=allItems.filter(i=>i.date===date&&inWorkspace(i,s.workspace));
 const sourceTitle=(i:PlanItem)=>sources.find(c=>c.sourceId===i.sourceId&&c.kind===i.sourceKind)?.title??i.title;
 function save(next:PlanItem[]){const state=usePersonal.getState();state.set({planItems:next,days:syncPriorities(state,next,date)});}
 function add(c:PlanCandidate){const state=usePersonal.getState(),all=materializeDayPlan(state,date);if(all.some(i=>i.date===date&&inWorkspace(i,state.workspace)&&i.sourceKind===c.kind&&i.sourceId===c.sourceId))return;const item:PlanItem={id:crypto.randomUUID(),sourceKind:c.kind,sourceId:c.sourceId,title:c.title,date,workspace:state.workspace,minutes:c.minutes,startTime:start||undefined,done:false,location:c.location};save([...all,item]);onPlace?.(c.location);}
 function reorder(id:string,target:string){const next=[...allItems],a=next.findIndex(i=>i.id===id),b=next.findIndex(i=>i.id===target);if(a<0||b<0)return;next.splice(b,0,next.splice(a,1)[0]);save(next);}
 useEffect(()=>{const handler=(e:Event)=>{const d=(e as CustomEvent).detail;if(d?.date!==date)return;const c=sources.find(c=>c.kind===d.kind&&c.sourceId===d.sourceId);if(c)add(c);};window.addEventListener('neo-plan-add',handler);return()=>window.removeEventListener('neo-plan-add',handler);},[date,sources,s.planItems]);
 const pending=items.filter(i=>!i.done),estimate=focusEstimate(pending);
 return <section className="w-card day-plan" onDragOver={e=>e.preventDefault()} onDrop={e=>{const c=sources.find(c=>c.id===e.dataTransfer.getData('application/guiding-item'));if(c)add(c);}}><div className="w-section-head"><div><span className="w-eyebrow">MEIN TAG · {date}</span><h2>Als Nächstes für mich.</h2></div><button className="w-icon" aria-label="Dem Tagesplan hinzufügen" onClick={()=>{setStart('');setPicker(true);}}><Plus size={19}/></button></div>
 <p className="w-muted">Aus deinem Journal, deinen Projekten und Kalendern. Per + oder Ziehen zusammenstellen.</p>
 <div className="day-plan-items">{items.map((i,n)=><article key={i.id} draggable onDragStart={e=>{setDrag(i.id);e.dataTransfer.setData('application/guiding-plan',i.id);}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.stopPropagation();reorder(e.dataTransfer.getData('application/guiding-plan')||drag,i.id);}} data-done={i.done}><button className="w-icon" aria-label={sourceTitle(i)+' als erledigt markieren'} onClick={()=>save(allItems.map(x=>x.id===i.id?{...x,done:!x.done}:x))}><Check size={16}/></button><button className="plan-title" onClick={()=>onPlace?.(i.location)}><small>{i.sourceKind==='goal'?'Ziel':i.sourceKind==='note'?'Notiz':i.sourceKind==='event'?'Termin':i.sourceKind==='project'?'Projekt':'Aufgabe'}</small><strong>{sourceTitle(i)}</strong></button><label className="plan-time"><span className="sr-only">Beginn für {sourceTitle(i)}</span><input type="time" value={i.startTime??''} onChange={e=>save(allItems.map(x=>x.id===i.id?{...x,startTime:e.target.value}:x))}/></label><label className="plan-duration"><input aria-label={'Dauer für '+sourceTitle(i)} type="number" min="1" max="1440" value={i.minutes} onChange={e=>save(allItems.map(x=>x.id===i.id?{...x,minutes:Math.max(1,Math.min(1440,Number(e.target.value)||1))}:x))}/> min</label><div className="plan-order"><button className="w-icon" aria-label={sourceTitle(i)+' nach oben'} disabled={!n} onClick={()=>reorder(i.id,items[n-1].id)}><ArrowUp size={13}/></button><button className="w-icon" aria-label={sourceTitle(i)+' nach unten'} disabled={n===items.length-1} onClick={()=>reorder(i.id,items[n+1].id)}><ArrowDown size={13}/></button><button className="w-icon" aria-label={sourceTitle(i)+' aus Tagesplan entfernen'} onClick={()=>save(allItems.filter(x=>x.id!==i.id))}><X size={14}/></button></div></article>)}</div>
 {!items.length&&<p className="journal-empty">Ein kleiner Schritt genügt. Wähle etwas, das heute Platz bekommen soll.</p>}
 <div className="plan-start"><span>{estimate.units} × 45 min · {estimate.breaks} × 10 min Pause zwischen den Blöcken</span><button className="w-btn w-btn-primary" disabled={!pending.length} onClick={()=>{useFocusStore.getState().startPlan(focusBlocks(pending.map(i=>({...i,title:sourceTitle(i)}))));window.dispatchEvent(new Event('neo-focus-play'));}}><Play size={16}/> Tagesplan im Fokus starten</button></div>
 <details><summary><Clock size={14}/> In eine bestimmte Zeit planen</summary><div className="plan-slot-add"><input aria-label="Zeit im Tagesplan" type="time" value={start} onChange={e=>setStart(e.target.value)}/><button className="w-btn" onClick={()=>setPicker(true)}><Plus size={16}/> Hier hinzufügen</button></div></details>
 {picker&&<Dialog title="Was bekommt heute Raum?" onClose={()=>setPicker(false)}><input autoFocus className="w-input" placeholder="Ziele, Notizen, Projekte oder Termine suchen …" value={q} onChange={e=>setQ(e.target.value)}/><div className="plan-source-list">{sources.filter(c=>c.title.toLowerCase().includes(q.toLowerCase())).map(c=>{const chosen=items.some(i=>i.sourceKind===c.kind&&i.sourceId===c.sourceId);return <button disabled={chosen} key={c.id} onClick={()=>add(c)}><span><small>{c.kind}</small><strong>{c.title}</strong></span><span>{c.minutes} min {chosen?'✓':'+'}</span></button>;})}</div>{!sources.length&&<p>Lege zuerst ein Ziel, eine Notiz, einen Termin oder eine Aufgabe an.</p>}<button className="w-btn" onClick={()=>setPicker(false)}>Fertig</button></Dialog>}</section>;
}
export function FocusPicker({onClose}:{onClose:()=>void}){
 const s=usePersonal(),today=localDate(),sources=usePlanCandidates(today),[selected,setSelected]=useState<PlanCandidate[]>([]),[q,setQ]=useState('');const estimate=focusEstimate(selected);
 return <Dialog title="Dein Fokusplan" onClose={onClose}><p>Wähle deine nächsten Schritte. Passe die Dauer an und bring sie mit den Pfeilen in deine Reihenfolge.</p><button className="w-btn" onClick={()=>setSelected(materializeDayPlan(s,today).filter(i=>i.date===today&&inWorkspace(i,s.workspace)&&!i.done).map(i=>({id:i.id,title:sources.find(c=>c.kind===i.sourceKind&&c.sourceId===i.sourceId)?.title??i.title,minutes:i.minutes,kind:i.sourceKind,sourceId:i.sourceId})))}>Heutigen Tagesplan übernehmen</button><input className="w-input" aria-label="Fokusauswahl suchen" placeholder="Ziele & Projekte suchen …" value={q} onChange={e=>setQ(e.target.value)}/><div className="plan-source-list">{sources.filter(c=>c.title.toLowerCase().includes(q.toLowerCase())).map(c=><label key={c.id}><input type="checkbox" checked={selected.some(i=>i.sourceId===c.sourceId&&i.kind===c.kind)} onChange={e=>setSelected(e.target.checked?[...selected,c]:selected.filter(i=>!(i.sourceId===c.sourceId&&i.kind===c.kind)))}/><span>{c.title}</span><small>{c.minutes} min</small></label>)}</div><ol className="focus-chosen">{selected.map((c,i)=><li key={c.id}><span>{c.title}</span><input aria-label={'Fokusdauer für '+c.title} type="number" min="1" max="1440" value={c.minutes} onChange={e=>setSelected(selected.map(x=>x.id===c.id?{...x,minutes:Math.max(1,Math.min(1440,Number(e.target.value)||1))}:x))}/><small>min</small><button aria-label={'Fokusreihenfolge '+c.title+' nach oben'} className="w-icon" disabled={!i} onClick={()=>{const next=[...selected];[next[i-1],next[i]]=[next[i],next[i-1]];setSelected(next);}}><ArrowUp size={14}/></button></li>)}</ol><div className="focus-estimate"><strong>{estimate.units} Fokusblöcke · {estimate.breaks} Pausen</strong><p>{estimate.minutes} min geschätzte Arbeit → {estimate.scheduled} min reserviert, plus 10 min Abschluss-Pause.</p></div><button disabled={!selected.length} className="w-btn w-btn-primary" onClick={()=>{useFocusStore.getState().startPlan(focusBlocks(selected));window.dispatchEvent(new Event('neo-focus-play'));onClose();}}><Play size={16}/> Fokusplan starten</button></Dialog>;
}
