"use client";
import {Pause,Play,RotateCcw,Square,Volume2,VolumeX} from 'lucide-react';
import {useFocusStore,useGlobalAudioStore,useUIExtStore,POMO_DURATIONS} from '@/lib/store';
import {useFocusMedia} from '@/lib/workspace/focus-media';
import {formatCountdown} from '@/lib/workspace/time';
import {useAssistantPreferences} from '@/components/assistant/Preferences';
export function FocusControls(){
 const f=useFocusStore(),a=useGlobalAudioStore(),ui=useUIExtStore(),m=useFocusMedia(),{preferences:p,update}=useAssistantPreferences();const work=f.pomodoroMode==='focus',muted=!p.sound||(work?a.workMuted:a.breakMuted);
 return <div className="header-focus-controls"><div className="focus-current-time"><small>{work?'Fokuszeit':'Bewusste Pause'}</small><strong>{formatCountdown(f.pomodoroSeconds)}</strong></div><div className="focus-actions"><button className="w-btn w-btn-primary" onClick={()=>{f.togglePomodoro();window.dispatchEvent(new Event('neo-focus-play'));}}>{f.pomodoroRunning?<Pause size={16}/>:<Play size={16}/>} {f.pomodoroRunning?'Pausieren':'Starten'}</button><button className="w-icon" onClick={()=>{f.resetPomodoro();f.togglePomodoro();window.dispatchEvent(new Event('neo-focus-play'));}} aria-label="Fokus neu starten"><RotateCcw size={16}/></button><button className="w-icon" onClick={()=>{f.stopPomodoro();ui.setPauseFullscreen(false);}} aria-label="Fokus stoppen"><Square size={16}/></button></div>
 {f.planQueue.length>0&&<p>{f.planIndex+1}/{f.planQueue.length} · {f.planQueue[f.planIndex]?.title}</p>}
 <label>Musik tauschen<select value={(work?ui.selectedWorkTrackId:ui.selectedBreakTrackId)??''} onChange={e=>(work?ui.setSelectedWorkTrackId:ui.setSelectedBreakTrackId)(e.target.value||null)}><option value="">Trinity · {work?'Waldlicht':'Abendstille'}</option>{(work?ui.workTracks:ui.breakTracks).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>
 <div className="focus-volume"><button className="w-icon" aria-label={muted?'Musik einschalten':'Musik ausschalten'} onClick={()=>{const toggle=work?a.toggleWorkMute:a.toggleBreakMute;if(!p.sound){update({sound:true});if(work?a.workMuted:a.breakMuted)toggle();}else toggle();window.dispatchEvent(new Event('neo-focus-play'));}}>{muted?<VolumeX size={16}/>:<Volume2 size={16}/>}</button><label>Lautstärke<input aria-label="Fokuslautstärke" type="range" min="0" max="1" step=".01" value={a.volume} onChange={e=>a.setVolume(Number(e.target.value))}/></label></div>
 <label>Musikposition · {formatCountdown(Math.floor(m.current))} / {formatCountdown(Math.floor(m.duration))}<input aria-label="Musikposition" type="range" min="0" max={m.duration||1} step="1" value={Math.min(m.current,m.duration||1)} disabled={!m.duration} onChange={e=>m.set({seek:Number(e.target.value)})}/></label>{m.blocked&&<button className="w-btn" onClick={()=>window.dispatchEvent(new Event('neo-focus-play'))}>Musik im Browser freigeben</button>}
 <a href="/dashboard/meditation">Eigene Musik & Pausenvideos verwalten →</a></div>;
}
export function FocusMini(){const f=useFocusStore();return <button className="focus-mini" aria-label="Fokustimer und Musik öffnen" title="Fokustimer und Musik" onClick={()=>window.dispatchEvent(new Event('neo-focus-controls'))} style={{'--progress':`${Math.max(0,Math.min(1,1-f.pomodoroSeconds/POMO_DURATIONS[f.pomodoroMode]))*360}deg`} as React.CSSProperties}><span>{formatCountdown(f.pomodoroSeconds)}</span></button>;}
