'use client';
import type {BirthResult} from '@/lib/workspace/birth';
const centers=[['head','Kopf',200,35],['ajna','Ajna',200,100],['throat','Kehle',200,165],['g','Identität',200,235],['heart','Herz',305,230],['spleen','Milz',85,310],['solarplexus','Solarplexus',315,310],['sacral','Sakral',200,325],['root','Wurzel',200,400]] as const;
const labels:Record<string,string>={sun:'Sonne',earth:'Erde',moon:'Mond',north_node:'Nordknoten',south_node:'Südknoten',mercury:'Merkur',venus:'Venus',mars:'Mars',jupiter:'Jupiter',saturn:'Saturn',uranus:'Uranus',neptune:'Neptun',pluto:'Pluto'};
export function HumanDesignDetails({hd}:{hd:NonNullable<BirthResult['hd']>}) {
 const point=(name:string)=>centers.find(c=>c[0]===name);
 const defined=new Set(hd.definedCenters),personality=new Set(Object.values(hd.p_).map(p=>p.gate)),design=new Set(Object.values(hd.d_).map(p=>p.gate));
 return <section className="w-card hd-details"><span className="w-eyebrow">HUMAN DESIGN · DEIN RECHNERISCHES PROFIL</span><h2>{hd.type} · {hd.profile}</h2><p className="w-muted">Autorität: {hd.authority}. Die Übersicht zeigt berechnete Zentren und Kanäle; sie ersetzt kein überprüftes Referenzchart.</p><div className="hd-layout"><svg viewBox="0 0 400 440" role="img" aria-label="Human-Design-Zentren und definierte Kanäle" className="hd-centers"><title>Deine Zentrenübersicht</title>{hd.definedChannels.map(c=>{const a=point(c.centers[0]),b=point(c.centers[1]);return a&&b?<line key={c.key} x1={a[2]} y1={a[3]} x2={b[2]} y2={b[3]} stroke="var(--theme-purple)" strokeWidth="5"><title>{c.gates.join('–')} · {c.name}</title></line>:null})}{centers.map(([id,label,x,y])=><g key={id}><rect x={x-45} y={y-23} width="90" height="46" rx="12" fill={defined.has(id)?'var(--theme-active)':'var(--theme-surface)'} stroke={defined.has(id)?'var(--theme-purple)':'var(--theme-border)'} strokeWidth="2"/><text x={x} y={y+4} textAnchor="middle" fill="var(--theme-text)" fontSize="11">{label}</text><title>{label}: {defined.has(id)?'definiert':'undefiniert'}</title></g>)}</svg><div><h3>Zentren</h3><ul className="hd-center-list">{centers.map(([id,label])=><li key={id}><span>{label}</span><strong>{defined.has(id)?'Definiert':'Undefiniert'}</strong></li>)}</ul><h3>Definierte Kanäle</h3>{hd.definedChannels.length?<ul>{hd.definedChannels.map(c=><li key={c.key}>{c.gates.join('–')} · {c.name}</li>)}</ul>:<p>Keine definierten Kanäle in diesem Chart.</p>}</div></div><details open><summary>Alle 64 Tore</summary><p className="w-muted">Lila: Persönlichkeit · Rosa: Design · beide Farben: beides. Nur berechnete Aktivierungen werden markiert.</p><div className="hd-gates">{Array.from({length:64},(_,i)=>i+1).map(g=><span key={g} data-personality={personality.has(g)||undefined} data-design={design.has(g)||undefined} title={`Tor ${g}: ${personality.has(g)?'Persönlichkeit':''} ${design.has(g)?'Design':''}`}>{g}</span>)}</div></details><details><summary>Planeten, Tore & Linien</summary><div className="hd-table-scroll"><table><thead><tr><th>Planet</th><th>Persönlichkeit</th><th>Design</th></tr></thead><tbody>{Array.from(new Set([...Object.keys(hd.p_),...Object.keys(hd.d_)])).map(k=><tr key={k}><th>{labels[k]||k}</th><td>{hd.p_[k]?`${hd.p_[k].gate}.${hd.p_[k].line}`:'–'}</td><td>{hd.d_[k]?`${hd.d_[k].gate}.${hd.d_[k].line}`:'–'}</td></tr>)}</tbody></table></div></details></section>;
}
