"use client";
import {useState} from 'react';
import {Plus,Pencil,Trash2} from 'lucide-react';
import {usePersonal,inWorkspace,AREAS,AREA_COLORS,type BrainNote,type Area} from '@/lib/workspace/personal';
import {Dialog} from './Dialog';
import {Attachments} from './Attachments';
import {PlaceField} from './PlaceField';
const COLORS=['#f5e6af','#d7e9df','#e7d9ef','#f4d9de','#d6e7f2'];
export function JournalNotes({date,onDateChange}:{date:string;onDateChange:(date:string)=>void}){
 const s=usePersonal(),[editing,setEditing]=useState<Partial<BrainNote>|null>(null),[all,setAll]=useState(false);
 const notes=s.notes.filter(n=>inWorkspace(n,s.workspace)&&(all||(n.date||n.updatedAt.slice(0,10)).startsWith(date.slice(0,7)))).sort((a,b)=>(b.date||b.updatedAt).localeCompare(a.date||a.updatedAt));
 const timeline=[...new Set([...s.notes.filter(n=>inWorkspace(n,s.workspace)).map(n=>(n.date||n.updatedAt).slice(0,7)),...Object.keys(s.days).filter(k=>k.startsWith(s.workspace+':')).map(k=>k.split(':')[1].slice(0,7)),date.slice(0,7)])].sort().reverse();
 return <aside className="journal-aside"><section className="journal-archive"><span className="w-eyebrow">MEINE ZEITSPUR</span><label>Jahr<input type="number" min="1900" max="2200" value={Number(date.slice(0,4))} onChange={e=>{if(Number(e.target.value)>=1900&&Number(e.target.value)<=2200)onDateChange(e.target.value+'-'+date.slice(5));}}/></label><label>Monat<select value={date.slice(5,7)} onChange={e=>onDateChange(date.slice(0,4)+'-'+e.target.value+'-01')}>{Array.from({length:12},(_,i)=><option key={i} value={String(i+1).padStart(2,'0')}>{new Date(2026,i,1).toLocaleDateString('de-AT',{month:'long'})}</option>)}</select></label><input aria-label="Journaldatum" type="date" value={date} onChange={e=>{if(e.target.value)onDateChange(e.target.value);}}/>{timeline.map(month=><button key={month} className="journal-archive-month" aria-pressed={date.startsWith(month)} onClick={()=>onDateChange(month+'-01')}>{new Date(month+'-01T12:00:00').toLocaleDateString('de-AT',{year:'numeric',month:'long'})}<span>{s.notes.filter(n=>inWorkspace(n,s.workspace)&&(n.date||n.updatedAt).startsWith(month)).length}</span></button>)}</section>
 <div className="w-section-head"><h2>Meine Notizzettel</h2><button className="w-icon" aria-label="Neue Journalnotiz" onClick={()=>setEditing({date,color:COLORS[0],area:'Leben',minutes:15})}><Plus size={18}/></button></div><label className="journal-all"><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>Alle Monate zeigen</label>
 <div className="journal-stickies">{notes.map((n,i)=><article className="journal-sticky" key={n.id} draggable onDragStart={e=>e.dataTransfer.setData('application/guiding-item','note:'+n.id)} style={{'--paper':COLORS.includes(n.color??'')?n.color:COLORS[i%COLORS.length],'--tilt':`${n.rotation??(i%2?1.6:-1.4)}deg`} as React.CSSProperties}><span className="sticky-tape"/><small>{n.date||n.updatedAt.slice(0,10)} · {n.area}</small><h3>{n.title}</h3><p>{n.body}</p>{n.attachments?.filter(a=>a.kind==='image').slice(0,1).map(a=><img key={a.id} src={a.url} alt={a.name} loading="lazy" referrerPolicy="no-referrer"/>)}<div className="sticky-tools"><button className="w-icon" aria-label={n.title+' bearbeiten'} onClick={()=>setEditing(n)}><Pencil size={15}/></button><button className="w-icon" aria-label={n.title+' in Tagesplan'} onClick={()=>{window.dispatchEvent(new CustomEvent('neo-plan-add',{detail:{kind:'note',sourceId:n.id,date}}));}}><Plus size={15}/></button><button className="w-icon" aria-label={n.title+' löschen'} onClick={()=>{if(confirm('Diese Notiz entfernen?'))s.set({notes:s.notes.filter(x=>x.id!==n.id)});}}><Trash2 size={14}/></button></div></article>)}</div>{!notes.length&&<p className="journal-empty">Eine Idee, ein Bild, ein Gedanke. Dein erster Zettel wartet.</p>}
 {editing&&<Dialog title={editing.id?'Deinen Gedanken weiterentwickeln':'Ein neuer Gedanke'} onClose={()=>setEditing(null)}><form className="w-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const note:BrainNote={...editing,id:editing.id??crypto.randomUUID(),workspace:editing.workspace??s.workspace,title:String(f.get('title')).trim(),body:String(f.get('body')),area:String(f.get('area')) as Area,date:String(f.get('date')),color:String(f.get('color')),rotation:Number(f.get('rotation')),minutes:Number(f.get('minutes')),links:editing.links??[],updatedAt:new Date().toISOString()};s.set({notes:editing.id?s.notes.map(n=>n.id===editing.id?note:n):[...s.notes,note]});setEditing(null);}}><label>Titel<input autoFocus name="title" required maxLength={200} defaultValue={editing.title}/></label><label>Gedanke<textarea name="body" rows={5} defaultValue={editing.body} maxLength={20000}/></label><div className="w-form-row"><label>Datum<input name="date" type="date" required defaultValue={editing.date||date}/></label><label>Lebensbereich<select name="area" defaultValue={editing.area??'Leben'}>{AREAS.map(a=><option key={a}>{a}</option>)}</select></label></div><div className="w-form-row"><label>Papierfarbe<select name="color" defaultValue={editing.color??COLORS[0]}>{COLORS.map((c,i)=><option value={c} key={c}>{['Honig','Salbei','Lavendel','Rosé','Himmel'][i]}</option>)}</select></label><label>Schräglage<input name="rotation" type="range" min="-4" max="4" step=".2" defaultValue={editing.rotation??-1.4}/></label><label>Geschätzte Minuten<input name="minutes" type="number" min="1" max="1440" defaultValue={editing.minutes??15}/></label></div><PlaceField value={editing.location} onChange={location=>setEditing({...editing,location})}/><Attachments items={editing.attachments} onChange={attachments=>setEditing({...editing,attachments})}/><button className="w-btn w-btn-primary">Gedanken behalten</button></form></Dialog>}</aside>;
}
export function JournalYear({date}:{date:string}){const s=usePersonal(),key=s.workspace+':'+date.slice(0,4),year=(s.years??{})[key]??{vision:'',success:'',release:''};return <details className="w-card journal-year"><summary>Mein Jahreskompass · {date.slice(0,4)}</summary>{([['vision','Das möchte ich wachsen lassen'],['success','So erkenne ich meinen Erfolg'],['release','Das darf ich loslassen']] as const).map(([field,label])=><label key={field}>{label}<textarea value={year[field]} rows={2} onChange={e=>s.set({years:{...(s.years??{}),[key]:{...year,[field]:e.target.value}}})}/></label>)}</details>;}
