"use client";
import {useState} from 'react';
import Link from 'next/link';
import {Plus,Trash2} from 'lucide-react';
import {usePersonal,AREAS,inWorkspace,type Attachment,type Place} from '@/lib/workspace/personal';
import {JOURNAL_VIEWS,type PlannerYear,type PlannerTrip} from '@/lib/workspace/planner';
import {materializeDayPlan,syncPriorities} from '@/lib/workspace/day-plan';
import {CalendarOverview} from './CalendarOverview';
import {Attachments} from './Attachments';
import {PlaceField} from './PlaceField';
const sections:Record<string,{title:string;intro:string;fields:[string,string][]}>={
 identity:{title:'Dein Lebensbild.',intro:'Was dich trägt und wohin du beitragen möchtest.',fields:[['life','Mein Lebensbild'],['mission','Meine Mission'],['values','Meine Werte'],['meaning','Was gibt meinem Leben Sinn?']]},
 discovery:{title:'Bei dir ankommen.',intro:'Raum für ehrliche Fragen, ohne fertige Antworten.',fields:[['joy','Was macht mich lebendig?'],['strengths','Meine Stärken'],['needs','Was brauche ich gerade?'],['learn','Was möchte ich über mich entdecken?']]},
 vision:{title:'Raum für deine Träume.',intro:'Ein Visionboard aus Worten, Bildern und nächsten Möglichkeiten.',fields:[['dreams','Meine großen Träume'],['idealDay','Mein idealer Tag'],['future','Mein Leben in fünf Jahren'],['visionStory','So möchte ich mich fühlen']]},
 strategy:{title:'Aus Vision wird Bewegung.',intro:'Wähle die Schritte, die du wirklich gehen kannst.',fields:[['priorities','Meine drei wichtigsten Jahresziele'],['steps','Konkrete nächste Schritte'],['resources','Menschen & Mittel, die helfen'],['reward','So feiere ich Fortschritte']]},
 growth:{title:'Wachsen in deinem Tempo.',intro:'Entdecken, was Raum braucht und was gehen darf.',fields:[['release','Was darf ich loslassen?'],['barriers','Was hält mich zurück?'],['beliefs','Welche Gedanken möchte ich neu formulieren?'],['support','Was würde den nächsten Schritt leichter machen?']]},
 rituals:{title:'Kleine Rituale, große Nähe.',intro:'Ein freundlicher Anfang und Abschluss für deinen Tag.',fields:[['morning','Mein Morgenritual'],['evening','Mein Abendritual'],['gratitude','Dafür bin ich dankbar'],['care','Das tut mir gut'],['affirmations','Worte, die mich begleiten']]},
 roadmap:{title:'Dein Weg durch das Jahr.',intro:'Von deinem Warum über Ziele zu täglichen Schritten und Rückblicken.',fields:[['start','Wo stehe ich heute?'],['milestones','Meine Etappen & Meilensteine'],['celebrate','Erfolge, die ich feiern möchte'],['next','Wohin führt der nächste Schritt?']]},
 notepad:{title:'Ideen dürfen frei sein.',intro:'Notizraum und persönliche Sammlung. Deine farbigen Zettel bleiben rechts.',fields:[['ideas','Ideen & Gedanken'],['notes','Freier Notizraum'],['index','Mein persönliches Inhaltsverzeichnis']]},
};
export function JournalNavigator({date,setDate,view,setView}:{date:string;setDate:(v:string)=>void;view:string;setView:(v:string)=>void}){return <nav className="journal-navigator w-card" aria-label="Alle Planerseiten"><span className="w-eyebrow">DEIN PLANER · ALLES FINDEN</span><label>Jahr<input className="w-input" type="number" min="1900" max="2200" value={Number(date.slice(0,4))} onChange={e=>{const y=Number(e.target.value);if(y>=1900&&y<=2200)setDate(`${y}-01-01`);}}/></label>{JOURNAL_VIEWS.map(v=><button key={v.id} aria-pressed={v.id===view} onClick={()=>setView(v.id)}><span>{v.label}</span><span aria-hidden="true">↗</span></button>)}<Link href="/dashboard/journal-legacy">Bisherige Ziele & Journale →</Link></nav>;}
export function JournalPages({view,date,setDate}:{view:string;date:string;setDate:(d:string)=>void}){
 const s=usePersonal(),key=`${s.workspace}:${date.slice(0,4)}`,year=s.years[key]??{vision:'',success:'',release:''},fields=year.fields??{},trips=year.trips??[];
 const [openTrip,setOpenTrip]=useState<string|null>(null),[status,setStatus]=useState('');
 function planTrip(t:PlannerTrip){const st=usePersonal.getState(),all=materializeDayPlan(st,t.from),sourceId='trip:'+t.id;if(all.some(i=>i.date===t.from&&inWorkspace(i,st.workspace)&&i.sourceId===sourceId)){setStatus('Diese Reise ist schon im Tagesplan.');return;}const next=[...all,{id:crypto.randomUUID(),sourceKind:'free' as const,sourceId,title:t.title,date:t.from,workspace:st.workspace,minutes:45,done:false,location:t.location}];st.set({planItems:next,days:syncPriorities(st,next,t.from)});setStatus('Reise im Tagesplan für '+t.from+' ergänzt. Im Kalender & Plan kannst du diesen Tag öffnen.');}
 function patch(p:Partial<PlannerYear>){const st=usePersonal.getState();st.set({years:{...st.years,[key]:{...(st.years[key]??{vision:'',success:'',release:''}),...p}}});}
 const field=(name:string,label:string)=><label key={name}>{label}<textarea className="w-input" rows={3} value={fields[name]??''} onChange={e=>patch({fields:{...fields,[name]:e.target.value}})}/></label>;
 if(view==='year')return <section className="journal-year-plan"><header><span className="w-eyebrow">DEIN JAHR {date.slice(0,4)}</span><h1>Zwölf Monate voller Möglichkeiten.</h1><p>Monate öffnen deinen Wochenplan. Ziele und Notizen bleiben miteinander verbunden.</p></header><CalendarOverview date={date} setDate={setDate} view="year" onMonth={()=>window.dispatchEvent(new CustomEvent('neo-journal-view',{detail:'month'}))} onEvent={()=>{}} onNew={()=>{}}/><div className="journal-year-months">{Array.from({length:12},(_,i)=>{const m=String(i+1).padStart(2,'0'),d=`${date.slice(0,4)}-${m}-01`;return <article className="w-card" key={m}><button className="journal-month-title" onClick={()=>{setDate(d);window.dispatchEvent(new CustomEvent('neo-journal-view',{detail:'Woche'}));}}>{new Date(d+'T12:00:00').toLocaleDateString('de-AT',{month:'long'})} ↗</button>{field('month:'+m,'Mein Fokus & Meilensteine')}<small>{s.goals.filter(g=>inWorkspace(g,s.workspace)&&g.due?.startsWith(d.slice(0,7))).length} Ziele · {s.notes.filter(n=>inWorkspace(n,s.workspace)&&(n.date??n.updatedAt).startsWith(d.slice(0,7))).length} Notizen</small></article>;})}</div><section className="w-card journal-year-areas"><h2>Mein Jahresplan nach Lebensbereichen</h2>{AREAS.map(a=>field('area:'+a,a))}{field('finances','Finanzen & Ressourcen')}{field('growth','Persönliche Entwicklung')}{field('spirituality','Spiritualität & innere Ruhe')}{field('family','Familie & Freundschaften')}{field('adventure','Freizeit & Abenteuer')}<div className="journal-page-media"><Attachments items={year.media?.year} onChange={items=>patch({media:{...year.media,year:items}})}/></div></section></section>;
 if(view==='month')return <CalendarOverview date={date} setDate={setDate} view="month" onEvent={e=>window.location.assign('/dashboard/calendar?date='+e.date)} onNew={()=>window.location.assign('/dashboard/calendar?date='+date)} onDay={()=>window.dispatchEvent(new CustomEvent('neo-journal-view',{detail:'Woche'}))}/>;
 if(view==='travel'){
  const update=(id:string,p:Partial<PlannerTrip>)=>patch({trips:trips.map(t=>t.id===id?{...t,...p}:t)});
  return <section className="journal-travel"><header className="w-section-head"><div><span className="w-eyebrow">UNTERWEGS · {date.slice(0,4)}</span><h1>Dein Reiseplan.</h1></div><button className="w-btn" onClick={()=>{const id=crypto.randomUUID();patch({trips:[...trips,{id,title:'Neue Reise',from:date,to:date,destination:'',notes:'',budget:'',packing:''}]});setOpenTrip(id);}}><Plus size={16}/> Reise planen</button></header>{status&&<p role="status">{status}</p>}{!trips.length&&<p className="journal-empty">Ein Sehnsuchtsort, ein freies Wochenende oder ein großes Abenteuer. Hier beginnt dein nächster Weg.</p>}{trips.map(t=><article className="w-card" key={t.id}><button className="journal-trip-title" aria-expanded={openTrip===t.id} onClick={()=>setOpenTrip(openTrip===t.id?null:t.id)}><strong>{t.title}</strong><span>{t.from} · {t.destination||'Ort noch offen'} ⌄</span></button>{openTrip===t.id&&<div className="journal-trip-fields">{(['title','destination','budget'] as const).map(k=><label key={k}>{{title:'Reise',destination:'Ziel & Route',budget:'Budget & Buchungen'}[k]}<input className="w-input" value={t[k]} onChange={e=>update(t.id,{[k]:e.target.value})}/></label>)}{(['from','to'] as const).map(k=><label key={k}>{k==='from'?'Von':'Bis'}<input className="w-input" type="date" value={t[k]} onChange={e=>update(t.id,{[k]:e.target.value})}/></label>)}{(['packing','notes'] as const).map(k=><label key={k}>{k==='packing'?'Packliste':'Ideen, Kontakte & Reisejournal'}<textarea className="w-input" rows={4} value={t[k]} onChange={e=>update(t.id,{[k]:e.target.value})}/></label>)}<PlaceField value={t.location} onChange={(location:Place|undefined)=>update(t.id,{location})}/><Attachments items={t.attachments} onChange={(attachments:Attachment[])=>update(t.id,{attachments})}/><div className="studio-actions"><button className="w-btn" disabled={!t.from||!t.title.trim()} onClick={()=>{planTrip(t);}}>Zum Tagesplan hinzufügen</button><button className="w-btn" onClick={()=>{if(confirm('Diese Reise entfernen?'))patch({trips:trips.filter(x=>x.id!==t.id)});}}><Trash2 size={15}/> Reise entfernen</button></div></div>}</article>)}</section>;
 }
 const page=sections[view];if(!page)return null;
 return <section className="journal-guided-page"><header><span className="w-eyebrow">DEIN JOURNAL · {date.slice(0,4)}</span><h1>{page.title}</h1><p>{page.intro}</p></header><div className="w-card journal-guided-fields">{page.fields.map(([k,l])=>field(view+':'+k,l))}</div><div className="w-card journal-page-media"><Attachments items={year.media?.[view]} onChange={items=>patch({media:{...year.media,[view]:items}})}/></div><p className="w-storage-note">Auf diesem Gerät gespeichert. Deine Sicherung unter Einstellungen nimmt diese Planerseiten mit.</p></section>;
}
