"use client";
import {useRef} from 'react';
import {usePersonal,AREAS,AREA_COLORS} from '@/lib/workspace/personal';
import {emptyDay} from '@/lib/workspace/planner';
const axes=['Stimmung',...AREAS,'Finanzen'];
export function LifeWheel({date,onDateChange}:{date:string;onDateChange:(d:string)=>void}){
 const s=usePersonal(),key=`${s.workspace}:${date}`,values=s.days[key]?.balance??{},svg=useRef<SVGSVGElement>(null);
 const point=(i:number,value:number)=>{const angle=i*Math.PI*2/axes.length-Math.PI/2,r=18+value*10;return [180+Math.cos(angle)*r,180+Math.sin(angle)*r];};
 const set=(area:string,value:number)=>{const st=usePersonal.getState(),k=`${st.workspace}:${date}`;st.set({days:{...st.days,[k]:{...(st.days[k]??emptyDay()),balance:{...st.days[k]?.balance,[area]:Math.max(1,Math.min(10,Math.round(value)))}}}});};
 const drag=(i:number,e:React.PointerEvent<SVGCircleElement>)=>{const node=svg.current!,matrix=node.getScreenCTM();if(!matrix)return;const p=node.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const cursor=p.matrixTransform(matrix.inverse()),x=cursor.x-180,y=cursor.y-180,angle=i*Math.PI*2/axes.length-Math.PI/2;set(axes[i],(x*Math.cos(angle)+y*Math.sin(angle)-18)/10);};
 const path=axes.map((a,i)=>point(i,values[a]??5).join(',')).join(' ');
 return <section className="life-wheel w-card" data-motion={s.motion} aria-label="Stimmung und Lebensrad"><div className="life-wheel-intro"><span className="w-eyebrow">DEIN INNERER KOMPASS</span><h2>Wie geht es dir heute?</h2><p>Ziehe die Lichtpunkte. Mit Tab und den Pfeiltasten kannst du sie ebenfalls einstellen.</p><label>Dein Tag<input className="w-input" type="date" value={date} onChange={e=>{if(e.target.value)onDateChange(e.target.value);}}/></label><small>Eigene Einschätzung · 1 bis 10<br/>Leere Punkte sind noch nicht bewertet.</small></div>
 <svg ref={svg} viewBox="0 0 360 360" className="life-wheel-graph" aria-label="Veränderbares Lebensrad"><defs><radialGradient id="life-glow"><stop stopColor="#9b6cb5" stopOpacity=".25"/><stop offset="1" stopColor="#467f92" stopOpacity=".02"/></radialGradient></defs><circle cx="180" cy="180" r="123" fill="url(#life-glow)"/>{[2,4,6,8,10].map(v=><circle key={v} cx="180" cy="180" r={18+v*10} fill="none" className="life-ring"/>)}{axes.map((a,i)=>{const [x,y]=point(i,10),[tx,ty]=point(i,13);return <g key={a}><line x1="180" y1="180" x2={x} y2={y} className="life-ring"/><text x={tx} y={ty} textAnchor="middle" dominantBaseline="middle">{a}</text></g>;})}<polygon points={path} className="life-shape"/><polygon points={path} pathLength="100" className="life-scan"/><g className="life-orbit"><circle cx="180" cy="58" r="3" fill="#ae81d3"/></g>{axes.map((a,i)=>{const [x,y]=point(i,values[a]??5);return <g key={a}><circle cx={x} cy={y} r="10" fill={AREA_COLORS[a]??'#aa80c9'} opacity=".2" pointerEvents="none"/><circle cx={x} cy={y} r="9" fill={values[a]===undefined?'var(--theme-surface)':AREA_COLORS[a]??'#aa80c9'} stroke={AREA_COLORS[a]??'#aa80c9'} strokeWidth="2" role="slider" tabIndex={0} aria-label={a+' im Lebensrad'} aria-valuemin={1} aria-valuemax={10} aria-valuenow={values[a]??5} aria-valuetext={values[a]===undefined?'Noch nicht bewertet':values[a]+' von 10'} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag(i,e);}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))drag(i,e);}} onKeyDown={e=>{if(['ArrowRight','ArrowUp','ArrowLeft','ArrowDown','Home','End'].includes(e.key)){e.preventDefault();set(a,e.key==='Home'?1:e.key==='End'?10:(values[a]??5)+(['ArrowRight','ArrowUp'].includes(e.key)?1:-1));}}}/></g>;})}<text x="180" y="184" textAnchor="middle" className="life-center">DEIN RHYTHMUS</text></svg>
 </section>;
}
