"use client";
import {useState} from 'react';
import Link from 'next/link';
import {Plus,Trash2} from 'lucide-react';
import {usePersonal} from '@/lib/workspace/personal';
import {emptyDay,weekDates} from '@/lib/workspace/planner';
export function PlannerExtras({date,view}:{date:string;view:string}){
 const s=usePersonal(),key=`${s.workspace}:${date.slice(0,4)}`,year=s.years[key]??{vision:'',success:'',release:''},[title,setTitle]=useState(''),habits=year.habits??[],dates=weekDates(date);
 if(view==='Woche')return <section className="w-card journal-habits"><header><span className="w-eyebrow">KLEINE SCHRITTE · DEINE WOCHE</span><h2>Was möchtest du pflegen?</h2></header><form onSubmit={e=>{e.preventDefault();if(!title.trim())return;s.set({years:{...s.years,[key]:{...year,habits:[...habits,{id:crypto.randomUUID(),title:title.trim()}]}}});setTitle('');}}><input className="w-input" aria-label="Neue Gewohnheit" placeholder="z. B. zehn Minuten draußen" maxLength={120} value={title} onChange={e=>setTitle(e.target.value)}/><button className="w-btn" disabled={!title.trim()}><Plus size={16}/> Hinzufügen</button></form>{!habits.length&&<p className="w-muted">Ein kleines Ritual reicht für den Anfang.</p>}<div className="habit-table"><div><span>Mein Ritual</span>{dates.map(d=><small key={d}>{new Date(d+'T12:00:00').toLocaleDateString('de-AT',{weekday:'short'})}<br/>{Number(d.slice(8))}</small>)}<span/></div>{habits.map(h=><div key={h.id}><strong>{h.title}</strong>{dates.map(d=>{const k=`${s.workspace}:${d}`;return <label key={d}><input type="checkbox" aria-label={h.title+' am '+d} checked={s.days[k]?.habits?.[h.id]??false} onChange={e=>{const st=usePersonal.getState();st.set({days:{...st.days,[k]:{...(st.days[k]??emptyDay()),habits:{...st.days[k]?.habits,[h.id]:e.target.checked}}}});}}/></label>;})}<button className="w-icon" aria-label={h.title+' entfernen'} onClick={()=>{if(confirm('Dieses Ritual aus der Liste entfernen?'))s.set({years:{...s.years,[key]:{...year,habits:habits.filter(x=>x.id!==h.id)}}});}}><Trash2 size={13}/></button></div>)}</div></section>;
 if(view==='Monatsrückblick'){const prefix='review:'+date.slice(0,7)+':';return <section className="w-card journal-guided-fields"><h2>Ressourcen & nächster Monat</h2>{[['income','Was kam herein?'],['spending','Wofür habe ich Geld & Zeit eingesetzt?'],['improve','Was möchte ich anders verteilen?'],['celebrate','Meine Belohnung für diesen Monat']].map(([id,label])=><label key={id}>{label}<textarea className="w-input" rows={3} value={year.fields?.[prefix+id]??''} onChange={e=>{const st=usePersonal.getState(),current=st.years[key]??year;st.set({years:{...st.years,[key]:{...current,fields:{...current.fields,[prefix+id]:e.target.value}}}});}}/></label>)}</section>;}
 if(view==='notepad'||view==='vision')return <Link className="w-btn" href="/dashboard/eden">Skizzen & Visionboard im Ideenboard öffnen →</Link>;
 return null;
}
