"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {collectSnapshot,restoreSnapshot,snapshotOf,SNAPSHOT_KEYS,SNAPSHOT_LABELS,type Snapshot,MAX_SNAPSHOT_BYTES} from "@/lib/workspace/snapshot";
type Cloud={userId:string;canSave:boolean;snapshot:{revision:number;payload:Snapshot;updated_at:string}|null};
function download(data:Snapshot){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`guiding-space-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function WorkspaceSync(){
  const [keys,setKeys]=useState<string[]>(SNAPSHOT_KEYS.filter(k=>k!=="trinity-birth-profiles-v1")),[cloud,setCloud]=useState<Cloud|null>(null),[status,setStatus]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false),[restoring,setRestoring]=useState<Snapshot|null>(null),[done,setDone]=useState(false);
  const owner=useRef("");const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
  const capture=()=>collectSnapshot(localStorage,keys);
  async function check(){const r=await fetch("/api/workspace/snapshot",{cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(r.status===401?"Bitte melde dich für deine private Serversicherung an.":d.error||"Server nicht erreichbar.");if(owner.current&&owner.current!==d.userId){owner.current=d.userId;setConsent(false);setCloud(null);throw Error("Das Konto hat gewechselt. Prüfe die Bereiche und bestätige die Sicherung neu.");}owner.current=d.userId;return d as Cloud;}
  async function action(work:()=>Promise<void>){if(busy)return;setBusy(true);setError("");setStatus("");try{await work();}catch(e){if(mounted.current)setError(e instanceof Error?e.message:"Sicherung nicht möglich.");}finally{if(mounted.current)setBusy(false);}}
  async function inspect(){const d=await check();if(!mounted.current)return;setCloud(d);setStatus(d.snapshot?"Deine Serversicherung ist bereit. Du entscheidest, welchen Stand du übernimmst.":"Noch keine Serversicherung. Dein lokaler Stand bleibt unverändert.");}
  async function push(){if(!cloud||!consent)return;const payload=capture();if(!Object.keys(payload.stores).length)throw Error("In den gewählten Bereichen liegen noch keine lokalen Daten.");const d=await check();if(d.snapshot?.revision!==cloud.snapshot?.revision){setCloud(null);setConsent(false);throw Error("Ein anderes Gerät hat einen neueren Stand gespeichert. Bitte Serverstand neu prüfen.");}
    const r=await fetch("/api/workspace/snapshot",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId:cloud.userId,revision:cloud.snapshot?.revision||0,payload})});const result=await r.json();if(!r.ok){if(r.status===409){setCloud(null);setConsent(false);}throw Error(result.error||"Sicherung fehlgeschlagen.");}if(!mounted.current)return;setCloud({...cloud,snapshot:{revision:result.revision,updated_at:result.updated_at,payload}});setStatus("Dein Stand ist privat gesichert. Melde dich auf einem anderen Gerät an und wähle Serverstand prüfen.");setConsent(false);}
  return <section className="workspace-sync"><p>Dein Gerät zuerst. Du entscheidest, ob du ausgewählte Bereiche als private Sicherung in deinem NEO-Konto ablegst. Der Abgleich erfolgt bewusst per Knopfdruck.</p>
    <fieldset disabled={busy||!!restoring||done}><legend>Bereiche für Export & Serversicherung</legend>{SNAPSHOT_KEYS.map(key=><label key={key}><input type="checkbox" checked={keys.includes(key)} onChange={e=>{setConsent(false);setKeys(old=>e.target.checked?[...old,key]:old.filter(k=>k!==key));}}/>{SNAPSHOT_LABELS[key]}</label>)}</fieldset>
    <p>Servernotizen, Rezepte und Radio-Merkliste sind bereits an dein Konto gebunden. Passwörter, Sitzung, Mikrofon-ID, Audio, fremde Apps und Agentenzugänge sind nicht Teil dieser Sicherung.</p>
    <div className="sync-actions"><button disabled={busy||!keys.length} onClick={()=>void action(async()=>{download(capture());setStatus("Sicherungsdatei erstellt.");})}>Datei sichern</button><button disabled={busy||done} onClick={()=>void action(inspect)}>Serverstand prüfen</button></div>
    {cloud&&<><p>Server: {cloud.snapshot?`${new Date(cloud.snapshot.updated_at).toLocaleString("de-DE")} · Version ${cloud.snapshot.revision}`:"Noch leer"}</p><label><input type="checkbox" checked={consent} disabled={busy||done} onChange={e=>setConsent(e.target.checked)}/>Diese lokalen Bereiche gehören zu meinem angemeldeten Konto. Ich möchte sie privat in Supabase sichern{cloud.snapshot?" und den bisherigen Serverstand ersetzen":""}.</label><button disabled={!consent||!cloud.canSave||busy||done} onClick={()=>void action(push)}>Auswahl auf Server sichern</button>{!cloud.canSave&&<p>Zum Speichern wird ein aktiver Förder- oder App-Zugang benötigt.</p>}{cloud.snapshot&&<button disabled={busy||done} onClick={()=>void action(async()=>{const d=await check();if(!mounted.current)return;setCloud(d);if(d.snapshot)setRestoring(snapshotOf(d.snapshot.payload));})}>Serversicherung wiederherstellen …</button>}</>}
    <label className="sync-import">Sicherungsdatei öffnen<input type="file" accept="application/json,.json" disabled={busy||done} onChange={e=>{const file=e.target.files?.[0];e.target.value="";if(file)void action(async()=>{if(file.size>MAX_SNAPSHOT_BYTES)throw Error("Datei zu groß (maximal 2 MB).");setRestoring(snapshotOf(JSON.parse(await file.text())));});}}/></label>
    {restoring&&<div className="sync-confirm" role="group" aria-label="Wiederherstellung prüfen"><p>Diese Bereiche werden auf diesem Gerät ersetzt: {Object.keys(restoring.stores).map(k=>SNAPSHOT_LABELS[k as keyof typeof SNAPSHOT_LABELS]).join("; ")}. Nicht enthaltene Bereiche bleiben erhalten. Schließe andere Tabs dieser App vorher.</p><p>Exportiere deinen lokalen Stand zuerst. Zusätzlich bleibt eine Rückkopie vor der Wiederherstellung auf diesem Gerät.</p><button disabled={busy||done} onClick={()=>void action(async()=>{download(collectSnapshot(localStorage,SNAPSHOT_KEYS));setStatus("Lokaler Stand vor Wiederherstellung exportiert.");})}>Lokalen Stand vorher exportieren</button><button disabled={busy||done} onClick={()=>void action(async()=>{restoreSnapshot(localStorage,restoring);setRestoring(null);setDone(true);setStatus("Wiederhergestellt. Lade die App neu, um den übernommenen Stand zu öffnen.");})}>Auf diesem Gerät übernehmen</button><button disabled={busy||done} onClick={()=>setRestoring(null)}>Abbrechen</button></div>}
    {done&&<button onClick={()=>window.location.reload()}>App neu laden</button>}{busy&&<p role="status">Wird geprüft …</p>}{status&&<p role="status">{status}</p>}{error&&<p role="alert">{error} {error.includes("melde dich")&&<Link href="/login">Zum Login</Link>}</p>}
  </section>;
}
